##################################################################################
# Makefile - Configuration file for GNU make (http://www.gnu.org/software/make/)
#            In practice, invoke the configuration file $(ROOTDIR)/Makefile
#
# Copyright (c) 2011 Sebastien Varrette <Sebastien.Varrette@uni.lu>
#               http://varrette.gforge.uni.lu
#                       __  __       _         __ _ _
#                      |  \/  | __ _| | _____ / _(_) | ___
#                      | |\/| |/ _` | |/ / _ \ |_| | |/ _ \
#                      | |  | | (_| |   <  __/  _| | |  __/
#                      |_|  |_|\__,_|_|\_\___|_| |_|_|\___|
#
#
# Available Commands: run `make help`
##################################################################################
ROOTDIR = ..

all:
	$(MAKE) -C $(ROOTDIR)

%:
	$(MAKE) -C $(ROOTDIR) $@

